###
### πR² Hugo Static Site Generator Configuration
### Theme: https://github.com/chipzoller/hugo-clarity
###
baseURL = 'https://pierreaoquadrado.github.io/'
languageCode = 'pt-BR'
defaultContentLanguage = 'pt-br'
publishDir = 'docs'
title = 'πR² - A Circulatura do Quadrado!'
theme = 'hugo-clarity'
description = 'Respostas para as dúvidas que você nem sabia que tinha!'
# keywords = ['matemática', 'sistemas', 'linux', 'windows']
homepage = 'https://pierreaoquadrado.github.io'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[author]
name = "πR²"

[params]
numberOfTagsShown = 12
dateFormat = '2006⋄01⋄02'
enableSearch = false
enableMathNotation = true
introDescription = 'Respostas para as dúvidas que você nem sabia que tinha!'
introURL = '/about'
mainSections = 'posts'
since = '2023'
websiteDomain = 'https://pierreaoquadrado.github.io'

[goldmark]
  [goldmark.renderer]
    hardWraps = false
    unsafe = true # change to false to disable inclusion of rawHTML and math functions
    xhtml = false
  [goldmark.extensions]
    typographer = false
  [highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = 'manni'
    tabWidth = 2

[menu]
[[menu.main]]
  name = 'Início'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'CPLEX'
  pageRef = '/tags/cplex'
  weight = 15

[[menu.main]]
  name = 'LaTeX'
  pageRef = '/tags/latex'
  weight = 17

[[menu.main]]
  name = 'Sobre'
  pageRef = '/about'
  weight = 20
